### PR TITLE
Fix typedefinitions of request, session and user

### PR DESCRIPTION
**Pull request by BeneStem**
Fixes: #279

### CODE REVIEW

**Comment by BeneStem** [comment]
Strange. Test says that "TypeScript compile error: Property 'application' does not exist on type '{ details: Session; sessionId: string; attributes: any; }'."
But in the real world it does :-/
What am I missing?

**Comment by BeneStem** [comment]
Updated the commit with force push to squash it... Not sure if this was the correct way to do it :/

**Comment by dblock** [comment]
Something related to the version of node? Maybe @lazerwalker can help?

**Comment by lazerwalker** [comment]
That's an expected `dtslint` failure — the existing TS tests essentially had an assertion on the old signature that `getSession()` returned an `alexa.Session` instead of a `session`.

Taking [this line](https://github.com/alexa-js/alexa-app/blob/master/types/test.ts#L10) and swapping in `request.getSession().application.applicationId` should fix it.

I think that + a changelog entry should have this PR good to go?

Thanks!

**Comment by BeneStem** [comment]
Ok. Will do that. Gimme a sec.

**Comment by BeneStem** [comment]
ok. done.

**Comment by BeneStem** [comment]
Thank you for being so patient and helpful :)

**Comment by BeneStem** [comment]
it's green. :P

**Comment by dblock** [comment]
@lazerwalker This is correct? Please merge.

**Pull request merged**
