### PR TITLE
Fixes bad utterance syntax is Docs. Fixes #89

### LINKED ISSUE #89: The schema generated from the number example doesn't work
```js
app.intent('StartIntent', {
        "slots": {
            "number" : "NUMBER"
        },
        "utterances": [
            "start {1-100|number}"
        ]
    },
```

This generates utterances:

```
StartIntent	start {one|number}
StartIntent	start {two|number}
StartIntent	start {three|number}
```

This doesn't work in sample utterances.

```
Error: There was a problem with your request: Incorrect syntax: A value may not be supplied for the slot 'number'. Occurred in sample 'StartIntent	start {one|number}' on line 4. 
```

### PR DESCRIPTION
**Pull request by Gowiem**

### CODE REVIEW

**Comment by Gowiem** [comment]
Is a CHANGELOG entry needed for this? Happy to update.

**Comment by dblock** [comment]
No need for CHANGELOG, this is great. 

One thing, I believe `NUMBER` is not the same as `AMAZON.NUMBER`, I think it needs to change in two more places, no?

**Comment by Gowiem** [comment]
@dblock Yeah, I've only seen it as `AMAZON.NUMBER` recently at least. I'll update later today.

**Comment by dblock** [comment]
Merged, thanks for doing this.

**Comment by dblock** [comment]
#89

**Pull request merged**
