### PR TITLE
Fix #152: mount a JSON body-parser after verifier middleware in Express integration.

### LINKED ISSUE #152: Test hangs in verifier
This test hangs for no reason: https://github.com/dblock/alexa-app/blob/test-hangs/test/test_alexa_verifier_middleware_hangs.js, the middleware never fires `on('end', function() { })`, not sure what's going on.

### PR DESCRIPTION
**Pull request by dblock**

### CODE REVIEW

**Comment by dblock** [comment]
@mreinstein You seem to understand the combination of these things much better than any of us, would appreciate your comments please.

**Comment by mreinstein** [comment]
I'm happy to help but I think if you guys are going to maintain modules that rely on express, you really should get more comfortable with it. Here is a really great interactive tut:

https://github.com/azat-co/expressworks

**Comment by dblock** [comment]
I'll queue that up. 

Can you code review this change and give it a 💚 @mreinstein?

**Comment by mreinstein** [comment]
I think `body-parser` is a dependency, not a devDependancy in `package.json`. Other than that good.

**Comment by dblock** [comment]
Amended.

**Comment by mreinstein** [comment]
Looks fine

**Comment by dblock** [comment]
FYI I gave you write permissions to this repo @mreinstein so you can merge things.

**Pull request merged**
