### PR TITLE
Update ssml.cleanse to stop removing spaces before decimals

### PR DESCRIPTION
**Pull request by aminimalanimal**
alexa-app was unexpectedly stripping spaces that occur before periods. Since periods are also decimals, this produced issues with the expected output of our bartender app's card text.

Things like:
> Ingredients: 2 oz Tanqueray No. TEN Gin, .5 oz Heavy cream, .5 oz Fresh lemon juice, .5 oz Fresh lime juice, .75 oz Simple syrup (one part sugar, one part water), 3 dashes Orange flower water, 1 Fresh egg white, and Club soda

were showing up as:
> Ingredients: 2 oz Tanqueray No. TEN Gin,.5 oz Heavy cream,.5 oz Fresh lemon juice,.5 oz Fresh lime juice,.75 oz Simple syrup (one part sugar, one part water), 3 dashes Orange flower water, 1 Fresh egg white, and Club soda

I think that this sort of cleansing should probably not be done at all, instead letting app developers to have control over their output, but this PR only removes the item that affected us. Perhaps the others will always be ideal to strip spaces for, but it's a hard thing to predict—after all, our use-case wasn't immediately obvious. :)

### CODE REVIEW

**Comment by aminimalanimal** [comment]
Apologies—I'm uncertain why the Travis CI build is failing.

**Comment by dblock** [comment]
The build failure is clearly about the changed behavior, so please run and fix the tests and maybe add more? LMK if you need help.

**Comment by aminimalanimal** [comment]
I just uploaded a change that passes the existing tests. Uncertain what the intention behind replacing `speak`/etc with a space was in the first place, so I don't know if this could potentially negatively impact something else.

**Comment by aminimalanimal** [comment]
btw, when I clicked on the travis-ci build bot earlier, it didn't provide me with any sort of _failed test_ output like running `npm run test` does; it just had some generic failure messages about environment variables or something.

**Comment by ericblade** [comment]
umm.. a possible? point? might be that SSML is intended for the voice output, not the card output.  Or is this some sort of auto-generated card, not a requested card?

In any case, I think that Alexa takes hints from the output punctuation, so not sure why we're pulling things out of it ..

**Comment by dblock** [comment]
The way the change is implemented right now needs additional tests that would fail with the old code, please. Otherwise it's easy to reintroduce a regression.

When I code reviewed this first the output changes in tests made sense, now they are back to the original version, which is probably not what was intended?

**Comment by aminimalanimal** [comment]
@ericblade The `cleanse` method is run to “remove all SSML to keep the card clean,” so even though this is in a file named `to-ssml`, it's really only meant to be used when converting from SSML.

**Comment by aminimalanimal** [comment]
@dblock Looking into...

**Comment by aminimalanimal** [comment]
> When I code reviewed this first the output changes in tests made sense, now they are back to the original version, which is probably not what was intended?

It seems to me like the expectations behind all existing tests are still valid, so I'm not sure what you mean. I'm still seeing the expected output that I made the change for (which broke the tests), and removing the space that was added while stripping the SSML tags un-broke the tests.

I've added a test to prevent regression.

Thanks for your patience and explanations in this matter. I haven't done much TDD, so the thought to add a test to ensure that my change stays in place didn't occur to me.

**Comment by dblock** [comment]
Looks good, thanks. Merging.

**Pull request merged**
