### PR TITLE
Document minimum node.js version, closes #143.

### LINKED ISSUE #143: Add section for which node versions are supported
If we plan to make any breaking changes that could potentially drop support for older versions of node, it's best to add a section in the README stating which versions **are** supported.

### PR DESCRIPTION
**Pull request by dblock**
Closes #143.

### CODE REVIEW

**Comment by tejashah88** [comment]
Looks good. I'll merge it!

**Comment by mreinstein** [comment]
I think this would be better served by the `engines` field in `package.json`. It doesn't clutter the README (which is already so long as to be unreadable) and enables npm to use the field programmatically.

**Comment by tejashah88** [comment]
IMO, it really doesn't clutter the README by that much, and it's visible so that anyone that just clicks on this module without scrolling too far down can see it.

**Comment by tejashah88** [comment]
The real problem with the clutter is that most of it just talks about using the library, which should practically be moved to the wiki section.

**Comment by dblock** [comment]
@mreinstein I did add an entry to package.json *and* a note in README. Did I miss something? 

One thing about package.json entry, its enforcement doesn't seem to do what you'd expect it to do, when you check out this code for example and run `npm install` with 0.10, it doesn't complain. I think it does when you include alexa-app into something else.

**Comment by dblock** [comment]
Speaking on README length (and I didn't write much of it), other libraries like [grape](https://github.com/ruby-grape/grape) have the longest README on planet earth, and multiple people praise it for being the best written thing ever. So YMMV. The important thing is that everything is documented. 

With a wiki it makes it hard to document something _together_ with code in a single pull request, so my vote would be not to do that.

**Comment by tejashah88** [comment]
That might be because there is a table of contents, otherwise people would hate to scroll through all of that.

**Comment by mreinstein** [comment]
> other libraries like grape have the longest README on planet earth, and multiple people praise it

This is anecdotal. I never suggested any kind of universal law about how long "good" READMEs are. 
All I'm saying is from the perspective of someone trying to use this, most don't want a tomb of stuff to sift through. A short thing to read that gets you up and running, with a pointer to more details as needed. 

If you can't shorten this at least put the stuff relevant to getting started at the top (what is this module, how do you start using it.) There's all this cruft at the top about stable releases, minimum node version, etc. most people just casually trying or using this don't care about that stuff.

**Comment by dblock** [comment]
It sounds like you have a good handle on what you'd like that README to be @mreinstein, so you're more than welcome to give it a shot as always.

**Comment by mreinstein** [comment]
yeah I'm just really slammed right now with contracting work. Maybe later tonight or tomorrow I'll separate the chaff from the wheat

**Comment by dblock** [comment]
My goal for now is to focus on getting a release of alexa-app and alexa-app-server that work well together (as you have suggested before @mreinstein). Will leave READMEs for later.

**Comment by mreinstein** [comment]
sounds good

**Pull request merged**
