### PR TITLE
allow utterance expansion in custom slot type synonyms

### PR DESCRIPTION
**Pull request by daanzu**

### CODE REVIEW

**Comment by daanzu** [comment]
Would need flatMap, not map. Could I interest you in reduce?

**Comment by kobim** [comment]
My bad, I forgot that the synonyms array might expand. I liked the previous implementation better, can you revert to that and I'll merge your changes?

**Comment by daanzu** [comment]
Removed reduce version.

**Comment by kobim** [comment]
Thank you for your contribution!

**Pull request merged**
