### PR TITLE
updated alexa-verifier-middleware to v1.0.0

### PR DESCRIPTION
**Pull request by tejashah88**
There has been many underlying changes to [alexa-verifier](https://github.com/mreinstein/alexa-verifier), particularly with improvements to the stability and security of the module. Recently it's reached v1.0.0, so I have thus updated the middleware module to reflect the recent changes.

### CODE REVIEW

**Comment by tejashah88** [comment]
Seems like there's a problem with node v9.2.0 and typescript? @lazerwalker 

image

**Comment by lazerwalker** [comment]
Just pushed a fix to this branch that should fix CI. TypeScript frustratingly changed things so that a formerly-optional config key is now mandatory, so adding it in should fix things.

Otherwise, this looks 👍 to me!

**Comment by lazerwalker** [comment]
Fixed up the various other tslint issues that arose as a result of bumping versions.

The only slightly sketchy one is that we seem to be running into a dtslint/compiler bug that means it was incorrectly yelling at us for what should have been a valid TS definition. Had to manually add in a linter config to ignore that rule while I open an issue with the actual dtslint repo.

Will leave merging to you, but I'm satisfied? Your stuff looks good, and CI's green.

**Comment by tejashah88** [comment]
Thanks for helping out with the typescript shenanigans!

**Pull request merged**
